services:
  - type: web
    name: mystic2-bot
    env: python
    plan: free
    pythonVersion: "3.11"
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    healthCheckTimeout: 30s

    envVars:
      - key: BOT_TOKEN
        sync: true
      - key: GROQ_API_KEY
        sync: true
      - key: GROQ_MODEL
        sync: true

    autoDeploy: true
