services:
  - type: web
    name: numerology-bot
    env: python
    plan: free
    pythonVersion: "3.13.4"  # либо 3.13 (публикует Render, можно 3.13.4)
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python main.py
    port: 8080
    healthCheckPath: /health
    healthCheckTimeout: 30s

    envVars:
      - key: BOT_TOKEN
        sync: true
      - key: GROQ_API_KEY
        sync: true
      - key: GROQ_MODEL
        sync: true

    autoDeploy: true

    cronJobs:
      - name: daily-cron
        schedule: "0 0 * * *"   # каждую полночь
        command: echo "cron works!"
