services:
  - type: web
    name: numerology-bot
    env: python
    plan: free
    pythonVersion: "3.11"      # 3.13.4 не подходит, используем 3.11
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python src/main.py   # <-- путь к вашему скрипту
    port: 8080
    healthCheckPath: /health
    healthCheckTimeout: 30s

    envVars:
      - key: BOT_TOKEN
        sync: true
      - key: GROQ_API_KEY
        sync: true
      - key: GROQ_MODEL
        sync: true

    autoDeploy: true

    cronJobs:
      - name: daily-cron
        schedule: "0 0 * * *"
        command: echo "cron works!"
